server:
  port: 8080
spring:
  config:
    activate:
      on-profile: default
  data:
    mongodb:
      host: localhost
      port: 27017
      database: viacera
      username: ales
      password: 8tron1Pa55word
      authentication-database: admin
