server:
  port: 8080
spring:
  config:
    activate:
      on-profile: default
  data:
    mongodb:
      host: host.docker.internal
      port: 27017
      database: reactiveSpringExample
      username: blacksea
      password: blacksea
      authentication-database: admin

---
spring:
  config:
    activate:
      on-profile: docker
  data:
    mongodb:
      host: mongo
      port: 27017
      database: reactiveSpringExample
      username: blacksea
      password: blacksea
      authentication-database: admin
