version: '3.8'

services:
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    networks:
      - harbata_net
    ports:
      - "27017:27017"
    volumes:
      - "vol_mongo:/var/lib/mongo"
    environment:
      MONGO_INITDB_ROOT_USERNAME: blacksea
      MONGO_INITDB_ROOT_PASSWORD: blacksea
      MONGO_INITDB_DATABASE: reactiveSpringExample
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    networks:
      - harbata_net
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: blacksea
      ME_CONFIG_MONGODB_ADMINPASSWORD: blacksea
  app:
    container_name: app
    build: ../
    networks:
      - harbata_net
    ports:
      - "8080:8080"
    links:
      - mongo-express
      - mongo
    depends_on:
      - mongo-express
      - mongo

networks:
  harbata_net:
    driver: bridge

volumes:
  vol_mongo:
